### ISSUE TITLE
Usability issue: Make --local-scheduler default when no remote scheduler is configured

### ISSUE THREAD

**Issue by samuell** [spotify/luigi#984] opened 2015-05-27 12:40 UTC
When using luigi for simpler, local workflows, without any remote scheduler, it is quite annoying to always have to type:

``` bash
./myworkflows.py --local-scheduler MyWorkflow --param1=val1
```

It would be much nicer to just need to run:

``` bash
./myworkflows.py MyWorkflow --param1=val1
```

That is, that `--local-scheduler` was the default setting, if no remote scheduler was configured.

**Comment by themalkolm** [comment] 2015-06-02 11:05
Totally agree! But not sure if it makes sense and how much it will break for all current luigi users.

**Comment by Tarrasch** [comment] 2015-06-02 11:10
It won't break if you first look at the available config.

**Comment by themalkolm** [comment] 2015-06-02 11:22
Before if you forgot to provide scheduler you fail, now you silently run locally. This is what I as talking about.

**Comment by Tarrasch** [comment] 2015-06-02 11:31
Ah true. Good point. It's probably better to not have this feature then. @samuell?

**Comment by themalkolm** [comment] 2015-06-02 11:34
I would say it is one of this moments when request is 100% valid and makes sense but due legacy reason it is not practical.

**Comment by samuell** [comment] 2015-06-02 11:37
Maybe a short-form of the `--local-scheduler` flag, like `-l`, would help? It certainly would for me :smile:

**Comment by erikbern** [comment] 2015-06-02 11:37
I think in some cases software should nudge people to do the right thing and by making it easier to use the local scheduler we would probably cause a lot of people not to discover the remote scheduler and miss one of the big selling points of Luigi. So I think it's worth forcing the user to type in some extra characters.

I'm fine with -l or something like that though

**Comment by Tarrasch** [comment] 2015-06-02 11:43
I'm usually for being expressive. What your use case @samuell? If you're using it interactively yourself, your shell should just be able to do `alias luigil = luigi --local-scheduler`. Also `-l` will be impossible to grep for.

Alternatively your config could have it to be using `--local-scheduler` by default?

**Comment by samuell** [comment] 2015-06-02 12:01
@Tarrasch Yeah, the `-l` suggestion was not to replace the `--local-scheduler` flag, just to provide an alternative, as is very common for unix/linux commandline tools.

Aliasing the `luigi` command is indeed one option, as well as adding it to the config. Didn't think about that (or, didn't know I can set that in config ... I should probably read up more carefully on the config :) ).

So, I could live with that, I guess. But an `-l` flag alias would definitely be even nicer IMO :smile: ... not the least for new users, before they have learned to fiddle with the config, or who might not be used to bash aliases.

**Comment by Tarrasch** [comment] 2015-06-02 14:31
Sorry, s/expressive/explicit ***. 

I think the problem is that if some random analyst who doesn't know luigi see's the `-l` flag, they'll have no idea what it means. As for it being specified in config, see https://github.com/spotify/luigi/blob/a0f73452c80173548a258c08f89b44edc4c771ae/luigi/interface.py#L72-L74. :) (i.e. `[core] local_scheduler: True`)

**Comment by Tarrasch** [comment] 2015-06-02 14:32
Hmm, if you specify it in config there's no way to unset it though, as bool parameters can only be turned on and not off. Hmm.

**Comment by mfcabrera** [comment] 2017-07-06 04:41
@Tarrasch  any decision on this usability issue?

**Comment by Tarrasch** [comment] 2017-07-06 09:53
For the reason mentioned by @erikbern above, I find that implementing this just adds negative value. I'm closing this for that. And this issue is already full with good workarounds I think.

**Closed by Tarrasch** 2017-07-06 09:53 UTC
Labels: Affects core, Small code change
