### ISSUE TITLE
contrib/sge - Python 3.5 breaks pickling (v2.1.1)

### ISSUE THREAD

**Issue by willu47** [spotify/luigi#1683] opened 2016-05-07 23:08 UTC
When using the SGEJobTask of the luigi.control.SGE module under python 3.5 and luigi version 2.1.1, I get the following error

``` python
Traceback (most recent call last):
  File "/hb/mnb/miniconda3/envs/testenv/lib/python3.5/site-packages/luigi/worker.py", line 175, in run
    new_deps = self._run_get_new_deps()
  File "/hb/mnb/miniconda3/envs/testenv/lib/python3.5/site-packages/luigi/worker.py", line 117, in _run_get_new_deps
    task_gen = self.task.run()
  File "/hb/mnb/miniconda3/envs/testenv/lib/python3.5/site-packages/luigi/contrib/sge.py", line 214, in run
    self._init_local()
  File "/hb/mnb/miniconda3/envs/testenv/lib/python3.5/site-packages/luigi/contrib/sge.py", line 205, in _init_local
    self._dump(self.tmp_dir)
  File "/hb/mnb/miniconda3/envs/testenv/lib/python3.5/site-packages/luigi/contrib/sge.py", line 238, in _dump
    pickle.dump(self, open(self.job_file, "w"))
TypeError: write() argument must be str, not bytes
```

I believe this is because the file object should be opened in bytes mode e.g. with the `'wb'` argument rather than `'w'`

The [python docs](https://docs.python.org/3.5/library/pickle.html#pickle.dump) refer to this:

> The file argument must have a write() method that accepts a single bytes argument. It can thus be an on-disk file opened for binary writing, an io.BytesIO instance, or any other custom object that meets this interface.

**Comment by willu47** [comment] 2016-05-07 23:18
Similar issues to #1494.

**Comment by tbonza** [comment] 2016-09-29 14:04
+1

**Comment by Lucas-C** [comment] 2017-02-23 14:11
I'm having the same issue

**Comment by Lucas-C** [comment] 2017-02-23 14:19
Should be fixed by https://github.com/spotify/luigi/pull/1819 I think.
I'm using luigi==2.2.0
This fix is included since v2.4.0
I think this issue can be closed

**Comment by Lucas-C** [comment] 2017-02-23 14:27
Confirmed: upgrading to v2.5.0 solved the issue for me

**Comment by Tarrasch** [comment] 2017-02-24 01:53
Closing then.

**Closed by Tarrasch** 2017-02-24 01:53 UTC
