### ISSUE TITLE
Add "History Tasks" tag to the website

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1163] opened 2015-08-25 09:49 UTC
It is quite useful to add "history" tag to index.html.

Currently: Upstream Failure, Failed Tasks, Running Tasks,..., Done Tasks.

A LOT and A LOT records are displayed in "Done Tasks". 
"History Tasks" is used for display the done tasks finished a week ago.

I know that it is configurable to set how long does a done task be displayed in the website.
But sometimes it is quite useful to check the history tasks.

**Comment by leafjungle** [comment] 2015-08-31 13:26
I mean, if all the tasks in the dependency graph is done. all its tasks will be put to "History Task".

**Comment by Tarrasch** [comment] 2015-08-31 13:30
I would wait with implementing this until #1086 is merged :)

**Comment by mfcabrera** [comment] 2017-07-07 15:44
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Closed by mfcabrera** 2017-07-07 15:44 UTC
Labels: WebUI
