### ISSUE TITLE
DictParameter fails when containing empty lists

### ISSUE THREAD

**Issue by sguermond** [spotify/luigi#2094] opened 2017-04-20 22:33 UTC
Related to [#1657](https://github.com/spotify/luigi/issues/1657#issuecomment-217066024), #1780 

The following error occurs at the end of the run when running a task with a DictParameter whose default is a (key -> empty list) pair or a (key -> empty list). 

```
Uncaught exception in luigi
Traceback (most recent call last):
  File "luigi/retcodes.py", line 74, in run_with_retcodes
    worker = luigi.interface._run(argv)['worker']
  File "luigi/interface.py", line 238, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "luigi/interface.py", line 198, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "luigi/execution_summary.py", line 418, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "luigi/execution_summary.py", line 356, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "luigi/execution_summary.py", line 147, in _get_str
    params = _get_set_of_params(tasks)
  File "luigi/execution_summary.py", line 190, in _get_set_of_params
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "luigi/execution_summary.py", line 190, in <setcomp>
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "luigi/parameter.py", line 793, in __hash__
    self.__hash = functools.reduce(operator.xor, hashes, 0)
TypeError: unhashable type: 'list'
```

The following two tasks will raise an error at the end of the run, even when completing successfully:
``` python
class TaskA(luigi.Task):
    dict_a = luigi.DictParameter(default = {"a": []})
```
``` python
class TaskB(luigi.Task):
    dict_b = luigi.DictParameter(default = {"b": [""]})
```

However, a non-empty list inside the default parameter prevents the error from happening:
``` python
class TaskC(luigi.Task):
    dict_c = luigi.DictParameter(default = {"c": ["c"]})
```
As will adding any other item to the dictionary, including a second empty list:
``` python
class TaskD(luigi.Task):
    dict_d = luigi.DictParameter(default = {"d": [], "e": []})
```

I think this is related to the fact that `ListParameters` are converted to tuples (#859, [#1614](https://github.com/spotify/luigi/pull/1614#issuecomment-203471407)) so they are immutable. The list inside the DictParameter isn't treated as a `ListParameter` before running through `FrozenOrderedDict`, so it breaks. However, I'm not sure why it doesn't break with more than one item in the dict.

**Comment by Tarrasch** [comment] 2017-04-21 08:33
Oh, I didn't realize you could pass lists as keys (arbitrary json stuff, [documentation says](http://luigi.readthedocs.io/en/stable/api/luigi.parameter.html#luigi.parameter.DictParameter)). Perhaps the [normalize](http://luigi.readthedocs.io/en/stable/api/luigi.parameter.html#luigi.parameter.DictParameter.normalize) method need to do some "recursive freezing". Note that the [FrozenOrderedDict](http://luigi.readthedocs.io/en/stable/api/luigi.parameter.html#luigi.parameter.FrozenOrderedDict) is from luigi, so I wouldn't be surprised if it has some weird unexpected way to calculate a hash (maybe it explains why it doesn't break with more than one item in the dict)

By the way, if you happen to have time to fix the code. Please also make FrozenOrderedDict and [DictParamEncoder](http://luigi.readthedocs.io/en/stable/api/luigi.parameter.html#luigi.parameter.DictParameter.DictParamEncoder) _private. :)

**Comment by Tarrasch** [comment] 2017-05-21 11:31
@sguermond, hi again. We just merged a patch that potentially could solve this issue. Can you try and see if the issue is resolved for you now?

**Comment by dlstadther** [comment] 2017-07-01 20:02
@sguermond Any update here? If the above patch resolved this, I'll close this issue. Thanks

**Comment by Tarrasch** [comment] 2017-07-02 15:13
We close for now to decrease the number of open issues. Feel free to re-open this at will if you still can reproduce this.

**Closed by Tarrasch** 2017-07-02 15:13 UTC
