### ISSUE TITLE
HdfsTarget warns: Parameter None is not of type string

### ISSUE THREAD

**Issue by luckyrandom** [spotify/luigi#1810] opened 2016-08-09 00:37 UTC
When HdfsTarget is used, it gives warning as following. Otherwise, it seems work fine.

```
..../python2.7/site-packages/luigi/parameter.py:234: UserWarning: Parameter None is not of type string.
  warnings.warn("Parameter {0} is not of type string.".format(str(x)))
```

**Comment by Tarrasch** [comment] 2016-08-09 03:33
Ah. This is bad. There's some parameter somewhere with a default value as `None`.

**Comment by anjackson** [comment] 2016-11-03 21:47
FWIW, I get this error because I've not set up email. i.e. I tracked it down to:

```
email(force_send=False, format=plain, method=smtp, prefix=None, receiver=None, sender=luigi-client@gleam.local)
('prefix', None, 'None')
('receiver', None, 'None')
```

**Comment by Tarrasch** [comment] 2016-11-04 02:12
@anjackson, Thanks for reporting this! But please open a new issue if you know you get this warning for a different reason. (in this particular case, I believe this is fixed in 2.3.3, but I might be wrong)

**Comment by labianchin** [comment] 2016-11-24 09:49
I noticed this happening when luigi is checking for task complete. The call hierarchy for this warning was:

HdfsTarget() -> luigi.contrib.hdfs.clients.get_autoconfig_client() -> luigi.contrib.hdfs.config.get_configured_hdfs_client() -> luigi.contrib.hdfs.config.hdfs()

I guess the problem is here https://github.com/spotify/luigi/blob/master/luigi/contrib/hdfs/config.py#L40. The call `os.getenv('HADOOP_USER_NAME')` call can return `None`. Should it be switched for something like `os.getenv('HADOOP_USER_NAME', 'default_user')`? Where `'default_user'` is something like `root` or `hadoop`.

**Comment by Tarrasch** [comment] 2016-11-24 09:55
@labianchin, in case you just want a change compatible with everything like it is now, just change it to the uncontroversial `os.getenv('HADOOP_USER_NAME', '')`. Please consider sending a PR. :)

**Comment by labianchin** [comment] 2016-11-24 15:57
Sure, I can create a PR. But it does not seem that `os.getenv('HADOOP_USER_NAME', '')` is appropriate. Before that value was `None` https://github.com/spotify/luigi/commit/d373bd07df6fac914ce1f97ca49f3a6621c1422b. I wonder if  it should be more appropriate to have a better handling for `None` in `parameter.py` `serialize()` method.

**Comment by Tarrasch** [comment] 2016-11-29 02:51
@labianchin, actually I think `None` is something we don't want to allow in luigi (why not use `''`?), as we potentially want to rename it to `StringParameter`. I'm pretty sure `os.getenv('HADOOP_USER_NAME', '')` is safe. If there happens to be any `if blah is None` patterns anywhere, tests would catch them.

**Comment by zwotzie** [comment] 2017-02-20 13:56
The problem is, that luigi want to have some entries in the configuration under [hdfs] for HdfsTarget.
I use client = snakebite and snakebite_autoconfig = True. This should automatically find all answers - and it does - except this warning. 

Minimalistic test:
`from luigi.contrib.hdfs.target import HdfsTarget
hdfs_target = HdfsTarget('/tmp/testfile')`

In this case luigi also "checks" these parameters: effective_user, namenode_host and tmp_dir. tmp_dir could not be empty.

For a quick workarround use config like:
`
[hdfs]
client = snakebite
snakebite_autoconfig = True
effective_user:
namenode_host:
tmp_dir: /tmp/somedir
`

**Comment by dlstadther** [comment] 2017-07-09 16:27
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [ ] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Closed by dlstadther** 2017-07-09 16:27 UTC
Labels: Affects contrib (only)
