### ISSUE TITLE
Issues with tasks containing spaces/parentheses/etc

### ISSUE THREAD

**Issue by erikbern** [spotify/luigi#130] opened 2013-07-17 02:05 UTC
See https://groups.google.com/forum/#!topic/luigi-user/TWwAtynX7Qc

and #125

**Comment by Tarrasch** [comment] 2017-07-05 16:03
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Comment by Tarrasch** [comment] 2017-07-05 16:03
Task names containing spaces/parentheses/etc? I suppose it was in the old days with cowboy serialization. That's fixed now. :)

**Closed by Tarrasch** 2017-07-05 16:03 UTC
