### ISSUE TITLE
Execution summary breaks for unhashable parameters

### ISSUE THREAD

**Issue by martinxsliu** [spotify/luigi#1387] opened 2015-11-10 23:55 UTC
The newly added `execution_summary` module in luigi 2.0 doesn't seem to work nicely with unhashable parameters, and running a task with any such parameter will raise a TypeError. It seems that the use of sets of parameters in the `_get_str` method is the cause of this error.

I'm not entirely sure what the logic is regarding that internal function, but is there a way of producing the execution summary without the use of sets?

**Comment by Tarrasch** [comment] 2016-03-22 10:40
This probably won't be fixed as it's not trivial. The good news is that the parameters don't need to be sortable anymore.

**Comment by mfcabrera** [comment] 2017-07-09 06:54
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ]  The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [x] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Closed by mfcabrera** 2017-07-09 06:54 UTC
Labels: bug
