### ISSUE TITLE
KeyboardInterrupt doesn't interrupt (parallel scheduling)

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1375] opened 2015-11-06 20:55 UTC
The KeyboardInterrupt handling in Luigi does not stop processing.

If a child receives the KeyboardInterrupt while processing specific tasks, the child will cleanup and close the tasks.  (Spark and Pig come to mind).  However, if the main process handles the KeyboardInterrupt, it doesn't tell the existing workers to stop.

As is, Worker.add() raises the exception, but doesn't tell any of the existing workers to stop.

Adding a pool.terminate() to the KeyboardInterrupt exception handler in Worker.add() would handle this issue.  The various tasks that call out to external tools (such as Spark and Pig) already handle SIGTERM gracefully.

**Comment by erikbern** [comment] 2015-11-06 21:05
This would be great to fix. Thanks for raising this. It's really annoying when libraries do this

**Comment by pb-cdunn** [comment] 2015-11-12 19:54
:+1:

**Comment by Tarrasch** [comment] 2015-11-27 06:43
Since I was pestered with this issue myself, I took a stab at this in #1427. Feel free to review it :)

**Comment by Tarrasch** [comment] 2016-03-22 10:45
Updated name to reflect the bugfix in #1429. Most users (who I assume don't do parallel scheduling) shouldn't face any issues anymore.

**Comment by mfcabrera** [comment] 2017-07-09 06:57
@Tarrasch  should I assume this won't be fixed or Should we keep it open?

**Comment by Tarrasch** [comment] 2017-07-09 09:06
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Closed by Tarrasch** 2017-07-09 09:06 UTC
Labels: bug

**Comment by Tarrasch** [comment] 2017-07-09 09:07
I close it. Anyone interested please see https://github.com/spotify/luigi/pull/1429.
