### ISSUE TITLE
Passing lists in on the command-line doesn't work properly

### ISSUE THREAD

**Issue by alexbw** [spotify/luigi#211] opened 2013-10-22 01:03 UTC
If you have a parameter that's declared as a list, e.g.

```python
import luigi
class ListTest(luigi.Task):
    my_list = luigi.Parameter([1,2,3], is_list=True)
    def run(self):
        print "\n"*5
        print self.my_list
        print "\n"*5
```

As long as you don't touch the defaults, or you pass in lists in Python, everything works fine.

`python list_test.py ListTest --local-scheduler`

prints (without the extra scheduling stuff)

```python
(1, 2, 3)
```

But when you try to pass in the list in the command-line, the list is never parsed properly.

`python list_test.py ListTest --my-list=[4,5,6] --local-scheduler`

```python
('[4,5,6]',)
```

I've tried all brands of character-escaping, but the list always comes in as a string. A solution I'm using as a stopgap is this:

```python
import ast
class TupleParameter(luigi.Parameter):
    def parse(self, x):
        return tuple(ast.literal_eval(x))


class ListTestWorking(luigi.Task):
    my_list = TupleParameter([1,2,3])
    def run(self):
        print "\n"
        print self.my_list
        print "\n"
```

`python list_test.py ListTestWorking --my-list=[4,5,6] --local-scheduler`

now works properly

```
(4, 5, 6)
```

`ast.literal_eval` is supposed to be a "safe" version of `eval`, meaning it'll only work on valid Python literal structures.

**Comment by jmmk** [comment] 2015-01-07 17:38
I ran into this today adding a list parameter to a task. The current "append" syntax seems clunky to me. The cleanest way I've found to do it with argparse is to use ```nargs='+'```. ([Documentation for nargs](https://docs.python.org/3/library/argparse.html#nargs))

In interface.py, [ArgparseInterface.add_parameter](https://github.com/spotify/luigi/blob/master/luigi/interface.py#L253), this would look something like:
```python
@classmethod
def add_parameter(cls, parser, param_name, param, prefix=None):
    description = []
    if prefix:
        description.append('%s.%s' % (prefix, param_name))
    else:
        description.append(param_name)
    if param.description:
        description.append(param.description)
    if param.has_value:
        description.append(" [default: %s]" % (param.value,))

    if param.is_list:
        parser.add_argument('--' + param_name.replace('_', '-'), help=' '.join(description), default=None, nargs='+')
    else:
        if param.is_boolean:
            action = "store_true"
        else:
            action = "store"
        parser.add_argument('--' + param_name.replace('_', '-'), help=' '.join(description), default=None, action=action)
```

**Comment by TylerJFisher** [comment] 2016-01-16 21:09
I was able to get around this issue by simply defining a custom parameter type 

```python
class ListParameter(luigi.Parameter):
    def parse(self, arguments):
        return arguments.split(' ')
```

Then passing a given `ListParameter` to a given luigi Task as follows:

```python
...
class Fetch(luigi.Task):    
     my_list = helper.luigi.ListParameter(default=[])
...
```

This allows you to pass in arguments as follows: `python myscript.py MyTask --my-list 'one two'`

```bash
¯\_(ツ)_/¯
```

**Comment by Tarrasch** [comment] 2016-01-17 00:31
Yes. That's the correct way @TylerJFisher, only that you must also implement `serialize()` (the opposite of `parse`).

I'm closing this. Since it's old and `is_list` is removed/deprecated core feature. If you want list like stuff do similar like what @TylerJFisher did above.

**Closed by Tarrasch** 2016-01-17 00:31 UTC

**Comment by palmeida** [comment] 2017-06-14 14:22
I was able to pass a list of strings in the command line by enclosing it in quotes:

luigi --module my_module MyTask --local-scheduler --my_parameter '["par1", "par2", "par3"]'

I also tried with a list of ints (--my_parameter '[1, 2, 3]') and it worked. I know the issue is closed, just leaving this here in case it's useful for anyone who is creating a parameter type just for this.
