### ISSUE TITLE
support of neo4j / implementation of neo4jTarget

### ISSUE THREAD

**Issue by ziky90** [spotify/luigi#1053] opened 2015-07-08 14:01 UTC
I would like to use luigi together with neo4j and I would like to ask if there was previously made some attempt to make something like neo4jTarget.
Would anyone appreciate me trying to work on this as a new PR?
Does anyone has some ideas of how this target should look like? For me to be able to incorporate this ideas and build on them.

**Comment by erikbern** [comment] 2015-07-08 14:55
I don't know of any previous work on it! Would be great to see a PR though – happy to review your idea if you want to outline it

**Comment by miku** [comment] 2015-07-08 14:57
When I implemented the [elasticsearch target](https://github.com/spotify/luigi/blob/a2fd8dc5546078560680fbf029fd35cb4d29f196/luigi/contrib/esindex.py) I just looked at already existing target implementations, e.g. for [postgres](https://github.com/spotify/luigi/blob/a2fd8dc5546078560680fbf029fd35cb4d29f196/luigi/postgres.py).

A target must implement [`exists`](https://github.com/spotify/luigi/blob/a2fd8dc5546078560680fbf029fd35cb4d29f196/luigi/target.py#L34), so you could start with code to answer this question. For the databases (and elastic as well), there is a marker table (or index, respectively), where updates are marked as done. Here's an example for [touch](https://github.com/spotify/luigi/blob/a2fd8dc5546078560680fbf029fd35cb4d29f196/luigi/contrib/mysqldb.py#L66) for MySQL.

I haven't worked with Neo4J, but I imagine that you could store this information inside a graph as well - maybe in a subgraph? Another idea - but I am not sure, since I haven't seen this much in the wild - is to mark the update *outside* the actual data store, e.g. in a file (you just keep care not to delete this file, since it would be the only indication of completion).

**Comment by dvetal** [comment] 2015-09-13 21:16
I for one would love to see something like neo4jTarget.

**Comment by mfcabrera** [comment] 2017-07-07 15:46
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Closed by mfcabrera** 2017-07-07 15:46 UTC
Labels: FeatureRequest
