### ISSUE TITLE
Task finished yet the luigi failed.

### ISSUE THREAD

**Issue by junchenfeng** [spotify/luigi#1657] opened 2016-04-18 02:29 UTC
I have py script contains the following task

class UpdateUserParameter(luigi.Task):
    udt = luigi.DateParameter()
    subject=luigi.Parameter()

    def output(self):
        return luigi.LocalTarget(local_proj_dir+'/data/crontab/{sub}/{dts}/is_user_parameter_updated.txt'.format(sub=self.subject, dts=self.udt.strftime('%Y-%m-%d')))
    def requires(self):
        return [users.UpdateUserParameterChain(subject=self.subject, udt=self.udt),
                users.UpdateUserKnowledgePointMasteryBuffer(subject=self.subject, udt=self.udt)
            ]

When the task runs, all task output is produced (including the master task) but the master task returns the following error:

Traceback (most recent call last):
  File "run_script.py", line 91, in <module>
    luigi.run()
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 210, in run
    return _run(*args, **kwargs)['success']
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 238, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 198, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 384, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 333, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 132, in _get_str
    params = _get_set_of_params(tasks)
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 173, in _get_set_of_params
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 173, in <setcomp>
    params[param] = {getattr(task, param[0]) for task in tasks}
TypeError: unhashable type: 'dict'

Because this error, other task depends on this cluster cannot be started. I cannot reliably reproduce this error and wonder how to fix it.

**Comment by tym-oao** [comment] 2016-05-02 21:59
I am seeing this same TypeError from execution_summary.py. (I have a bunch of Tracebacks much like @junchenfeng's OP) I'm not sure when this first appeared, but based on the commit history for that file, my best guess is it was something introduced here: https://github.com/spotify/luigi/commit/3b249492a4cf203a988b47545b72425bbbb2a68f - the next commit previous was back in March and I think I would have noticed it before a few days ago.

For my purposes, this is just annoying, but doesn't really break anything. I believe this code only prints out a human-readable summary status at the end of a workflow. All tasks still get marked as DONE by the scheduler in appropriate ways.

I'll see if there's anything I might be able to contribute here by way of a PR to fix, but at the moment I must admit I don't quite understand the code here or what might be going wrong exactly, so this may well be a job for someone more skilled than myself. I am checking it out, though.

**Comment by Tarrasch** [comment] 2016-05-04 02:15
@tym-oao Cool. if you can find a minimal self-contained example (and post an easier-to read error report than this issue). I might at least guide you to how to fix the issue.

**Comment by tym-oao** [comment] 2016-05-04 16:22
@Tarrasch This took a few tries, but at this point I believe the issue with `execution_summary.py` occurs whenever a workflow invokes a Task that uses a `DictParameter`. This would also explain the timing better than the commit I referred to in my previous comment — I simply wasn't using the `DictParameter` type in my code until I made some changes recently. Here's a very simple case:

```
import luigi


class JobA(luigi.Task):
    fdict = luigi.DictParameter(default={'foo': 'bar'})
    def run(self):
        with self.output().open('w') as out:
            out.write(self.fdict['foo'])

    def output(self):
        return luigi.LocalTarget('/tmp/outfile')
```

Which results in:

```
Traceback (most recent call last):
  File "/Users/thomas/.virtualenvs/tmp-3d4605015530c32/lib/python3.5/site-packages/luigi/retcodes.py", line 61, in run_with_retcodes
    worker = luigi.interface._run(argv)['worker']
  File "/Users/thomas/.virtualenvs/tmp-3d4605015530c32/lib/python3.5/site-packages/luigi/interface.py", line 238, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/Users/thomas/.virtualenvs/tmp-3d4605015530c32/lib/python3.5/site-packages/luigi/interface.py", line 198, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "/Users/thomas/.virtualenvs/tmp-3d4605015530c32/lib/python3.5/site-packages/luigi/execution_summary.py", line 388, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/Users/thomas/.virtualenvs/tmp-3d4605015530c32/lib/python3.5/site-packages/luigi/execution_summary.py", line 337, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/Users/thomas/.virtualenvs/tmp-3d4605015530c32/lib/python3.5/site-packages/luigi/execution_summary.py", line 123, in _get_str
    attributes = {getattr(task, tasks[0].get_params()[0][0]) for task in tasks}
  File "/Users/thomas/.virtualenvs/tmp-3d4605015530c32/lib/python3.5/site-packages/luigi/execution_summary.py", line 123, in <setcomp>
    attributes = {getattr(task, tasks[0].get_params()[0][0]) for task in tasks}
TypeError: unhashable type: 'dict'
```

As I mentioned before, the actual task runs as expected, output is written correctly, any upstream dependencies would presumably fire as expected, etc. Only the Execution Summary at the end of the log output fails to print, replace with the Traceback immediately above.

Hope that helps.

**Comment by cyyuan2002** [comment] 2016-05-04 20:28
I just encountered exactly same problem... 
Here are my codes
`
import luigi

paras = {}

outfile = {'outfile': 'word.txt'}

paras['SimpleTask'] = outfile


class SimpleTask(luigi.Task):
    """
    SimpleTask prints Hello World!.
    """
    my_paras = luigi.DictParameter()

    def output(self):
        st_para = self.my_paras['SimpleTask']
        tar_file = st_para['outfile']
        return luigi.LocalTarget(tar_file)

    def run(self):
        words = [
            'apple',
            'banana',
            'grapefruit'
        ]
        with self.output().open('w') as f:
            for word in words:
                f.write('{word}\n'.format(word=word))


class DecoratedTask(luigi.Task):
    """
    DecoratedTask depends on the SimpleTask
    """

    def requires(self):
        return SimpleTask(my_paras=paras)

    def output(self):
        return luigi.LocalTarget('letter_counts.txt')

    def run(self):

        # read in file as list
        with self.input().open('r') as infile:
            words = infile.read().splitlines()

        # write each word to output file with its corresponding letter count
        with self.output().open('w') as outfile:
            for word in words:
                outfile.write(
                        '{word} | {letter_count}\n'.format(
                            word=word,
                            letter_count=len(word)
                            )
                        )


if __name__ == '__main__':
    luigi.run(["--local-scheduler"], main_task_cls=DecoratedTask)
`

And the other question is how I can put paras in luigi.run part, rather than put it in "class DecoratedTask", Thanks!

**Comment by Tarrasch** [comment] 2016-05-05 03:08
@tym-oao. Ok I see the problem and solution. We use a FrozenOrderedDict which thankfully *is* hashable. But the problem is when we have default values that are normal dict. Like `DictParameter(default=dict(blah="foo"))`. One way to fix this:

 1. Add test case in execution summary code
 2. Run test and see it fails as expected
 3. (the fix): Go to this code https://github.com/spotify/luigi/blob/31d9d81291ac697721594856613a653b5c2f6162/luigi/parameter.py#L747-L803, To `DictParameter` class add a `normalize` method. Ensuring that it's converts it's input to a value of type `FrozenOrderedDict`. Then the parameter-values will actually be hashable.
 4. Run tests and hopefully it passes.

@tym-oao. Do you want to send a PR? :)

**Comment by junchenfeng** [comment] 2016-05-17 01:52
I am a bit confused since my task does not (explicitly) contain DictParameter, unless DateParameter is a subclass of DictParameter.

**Comment by Tarrasch** [comment] 2016-05-17 02:04
@junchenfeng, oh that's interesting. Maybe it's a separate bug from @tym-oao. Or perhaps the dependencies somewhere down the dependency tree has tasks with DictParameters?

**Comment by junchenfeng** [comment] 2016-05-17 02:15
The culprit is ExternalHiveTask() whose partition parameter is a dict. Curiously, when I resort to a hand written ExternalTask, it is OK. 

I guess the problem is specific to the require method.

**Comment by Tarrasch** [comment] 2016-05-18 02:09
Thanks for digging in to this @junchenfeng. Do we have any volunteer to fix this (relatively serious) issue?

**Comment by nugend** [comment] 2016-06-03 15:42
Hey @Tarrasch I'll see if I can handle this over the weekend.  Do you think what @tym-oao posted would serve as a good basis for a failing test case?

**Comment by Tarrasch** [comment] 2016-06-06 02:42
@nugend, kindof. It's even simpler, just copy one of the tests from `execution_summary_test.py` and use a DictParameter somewhere. I think that's it.

**Closed** 2016-06-08 02:26 UTC
