### ISSUE TITLE
exceptions in Task.output() don't show up in the Central Scheduler website

### ISSUE THREAD

**Issue by graingert** [spotify/luigi#1141] opened 2015-08-18 14:22 UTC
These errors do trigger logging and signals etc, but do not show up in the central scheduler web page.

**Comment by graingert** [comment] 2015-08-18 14:25
Ah my mistake, these errors do trigger logging and signals etc, but do not show on the central scheduler web page.

**Comment by erikbern** [comment] 2015-08-18 14:32
fine if i close this?

**Comment by graingert** [comment] 2015-08-18 14:33
@erikbern updated issue

**Comment by erikbern** [comment] 2015-08-18 14:41
this is a feature request then, not an issue :)

would be amazing if someone could implement this

**Comment by graingert** [comment] 2015-08-18 14:42
@erikbern there's no distinction on the GitHub tracker :(

**Comment by mfcabrera** [comment] 2017-07-07 15:39
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Closed by mfcabrera** 2017-07-07 15:39 UTC
