### ISSUE TITLE
Access task logs in luigid

### ISSUE THREAD

**Issue by mikekap** [spotify/luigi#1512] opened 2016-01-15 04:15 UTC
It would be really nice if luigi intercepted logger.XXX calls & sent them somewhere to be viewed with luigid (up to some reasonable limit). It would help a lot in debugging broken tasks or checking that a task is actually doing something without finding which actual process is running it.

For bonus points, intercept sys.stdout/sys.stderr entirely :)

**Comment by knassiri** [comment] 2016-06-20 13:19
Duplicate of #1008

**Comment by Tarrasch** [comment] 2017-01-17 09:54
Thanks for the triaging work @knassiri. I'm closing this as it's a (much better worded) duplicate of #1008.

**Closed by Tarrasch** 2017-01-17 09:54 UTC
