### ISSUE TITLE
Memory leak at the manager

### ISSUE THREAD

**Issue by rantav** [spotify/luigi#430] opened 2014-09-08 05:44 UTC
Following a corespondence with @erikbern on the mailing list.

I seem to have a memory leak on luigid (the server). 

![process_inspector_for_luigi-prod_-_new_relic](https://cloud.githubusercontent.com/assets/87037/4181499/e6f9e9c6-371a-11e4-9f43-aa385399262a.png)

We have a couple of thousands of tasks and after a few weeks memory usage of luigid grows significantly. 

Erik: It's probably some dict of all tasks that we don't clean in the scheduler

**Comment by ronsher** [comment] 2015-10-01 13:07
Any news regarding this issue?

**Comment by erikbern** [comment] 2015-10-01 13:48
not afaik but if it's an issue for you, i would love it if you can debug

**Comment by Tarrasch** [comment] 2015-10-01 14:00
I doubt this is still an issue today. @ronsher, did you run into this? @rantav, are you guys still using luigid and experiencing this issue?

Otherwise I would just close this ticket.

**Comment by ron-totango** [comment] 2015-10-01 14:25
Yes, we have a constant rise in the memory consumption so we restart it
from time to time. We currently don't have capacity to debug so I'm hoping
to get a fix...
בתאריך 1 באוק׳ 2015 5:00 אחה״צ,‏ "Arash Rouhani" <notifications@github.com>
כתב:

**Comment by Tarrasch** [comment] 2015-10-01 14:38
Have you configured the scheduler to retain old tasks? If you visit the visualiser, do you see old tasks still?

I might look at it if you can provide a way to reproduce this.

**Comment by ronsher** [comment] 2015-10-01 14:54
This is happening in our production environment so I don't think we can provide direct access.
Not sure if it was mentioned before, but the way we use luigi is to run python tasks that create Java processes. Don't know if this should affect anything, but just so you know.

@rantav - can you suggest a simple environment to repro this?

**Comment by Tarrasch** [comment] 2015-10-01 14:57
@ronsher. That shouldn't matter. Luigid is the server, and it doesn't know if the luigi clients run java jobs or not. I think most enterprises (including Spotify) have many luigi tasks shelling out to java processes.

**Comment by ronsher** [comment] 2015-10-03 06:00
@aeronite  / @nogazit, can we create such an environment for debugging?

**Comment by rantav** [comment] 2015-10-04 17:00
Hi guys, what's the version of luigid running at Totango?
If it's the version that was there when I left then it's probably quite old so first thing to try is an upgrade.

**Comment by ronsher** [comment] 2015-10-04 17:08
How can I tell which version is running?
בתאריך 4 באוק׳ 2015 8:01 אחה״צ,‏ "Ran Tavory" <notifications@github.com>
כתב:

**Comment by aeronite** [comment] 2016-05-01 09:34
@Tarrasch ,We just upgraded to Luigi 2.1.1 several weeks ago and the memory leak is still the same :(
Are we the only ones having this issue?

**Comment by aeronite** [comment] 2016-05-01 09:53
If this helps, we're using these non default settings in the cnf file:

[scheduler]
# 24h
remove-delay: 86400 

[scheduler]
record_task_history: true

**Comment by Tarrasch** [comment] 2016-05-04 02:12
Ah, it's perhaps in the code related to task_history. Many people use it but I know a lot don't. I've for one not used it myself. I think it's fine to crosspost this to the mailing list in case somebody else knows anything. Good luck.

**Comment by ron-totango** [comment] 2016-05-04 06:41
Looks like disabling history did the trick (we made the change on May 1st)
@rantav - FYI

![image](https://cloud.githubusercontent.com/assets/7913829/15006802/4fdc7f06-11dc-11e6-9d4b-f53d35ad1590.png)

**Comment by rantav** [comment] 2016-05-04 07:03
yeah, I figured that our, but IIRC we wanted to history. I don't remember
the details but I think we needed this for correctness to prevent unwanted
retries in the past 24h.

On Wed, May 4, 2016 at 9:41 AM, ron-totango <notifications@github.com>
wrote:

> Looks like disabling history did the trick (we made the change on May 1st)
> @rantav <https://github.com/rantav> - FYI
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7913829/15006802/4fdc7f06-11dc-11e6-9d4b-f53d35ad1590.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/luigi/issues/430#issuecomment-216759124>
>



-- 
/Ran
yodas.com

**Comment by Tarrasch** [comment] 2016-05-04 07:22
The history shouldn't affect execution. Though a lot of users want it because they want to know what have previously happened.

**Comment by levipierce** [comment] 2016-05-11 19:20
We are also seeing the memory leak running ~1000 workers memory usage grows until it dies.  We had to mount a large EBS volume for a swap disk to get around the issue.  It is very reproducible.

**Comment by ronsher** [comment] 2016-05-11 20:58
Try to disable history like we did
בתאריך 11 במאי 2016 10:20 אחה״צ,‏ "levipierce" <notifications@github.com>
כתב:

**Comment by binarybana** [comment] 2016-05-11 21:46
(speaking about the problem mentioned by @levipierce): We're using the default configuration which AFAICT means we're not using history. This is with 1000 workers and 6000 tasks in a single DAG.

**Comment by Tarrasch** [comment] 2016-05-12 02:41
@levipierce and @binarybana. Are you perchance using the assistants feature? It previously had some serious bug and I saw it just becoming slower with time and consume memory (but you say it's just eating memory but serving requests at the same speed?).  Are you running a version after this patch? https://github.com/spotify/luigi/pull/1603

**Comment by binarybana** [comment] 2016-05-12 22:30
@Tarrasch: We're not using assistants, and we're using 2.1.1 which looks to have that patch. We're going to try and build a minimal reproduction and try some memory profiling and see what we can find on our side when we get a chance.

**Comment by Tarrasch** [comment] 2016-05-13 02:20
Sounds good.

**Comment by Tarrasch** [comment] 2016-07-18 09:00
Closing this. I assume there is no serious memory leak bug lingering from two years ago. Feel free to repoen this issue if you deem necessary, alternatively opening a new similar issue.

**Closed by Tarrasch** 2016-07-18 09:00 UTC

**Comment by ozzieba** [comment] 2017-12-04 18:09
We are still running into this, with Luigi 2.6.2.
Looking at the [code](https://github.com/spotify/luigi/blob/56fbbcb9be4c97a88c25fa527881f5bbade9cd41/luigi/db_task_history.py#L109) , it seems like self.tasks is storing all the tasks in history, and never gets cleaned. Could we add some kind of process to periodically clean old tasks?
